### ISSUE TITLE
Return type annotations 

### ISSUE THREAD

**Issue by antoinelb** [kalekundert/vim-coiled-snake#12]
Under the following conditions, the return type doesn't get included in the fold:
- Return on a new line with the parenthesis (such as black formats)
- Whitespace in the type annotation (after comma)
For example, this gets folded:
```
def get_admission_tables(
    profiles: List[str]
) -> Tuple[pd.DataFrame,pd.DataFrame,pd.DataFrame]:
```
, but not this:
```
def get_admission_tables(
    profiles: List[str]
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
```

**Comment by kalekundert** [comment]
Thanks for the bug report.  The support for type annotations has always been kinda hacky, so I'll try to put together something more robust this weekend.  Or failing that, I'll at least add another hack to handle this case right. :-)

**Comment by antoinelb** [comment]
Thanks!

**Comment by kalekundert** [comment]
I ended up just adding another hack, although I think it should cover any possible return annotation.  Let me know if you run into any other failure cases, though.
