### ISSUE TITLE
When first opening a new file, every close ation will be applied to the entire file.

### ISSUE THREAD

**Issue by josefson** [kalekundert/vim-coiled-snake#17]
I wish there would be an option for us to fold whatever we wanted instead of everything by default.
by setting nofoldenable, allows me to open the file not folded, however when trying to fold a simple function causes the entire file to be folded.

**Comment by kalekundert** [comment]
Sorry for not responding earlier.  I'm not quite sure what you mean, though.  For me, `zc` and `zo` only affect the fold under the cursor.  Can you give me a more specific sequence of what hotkeys you press and what happens?

**Comment by subnut** [comment]
@josefson I am sure you are looking for the `foldlevel` option. Try putting this line in your vimrc -
```vim
set foldlevel=999
```

If this is not what you are looking for, feel free to re-open this issue.
