### ISSUE TITLE
Folds do not work properly with string breaks

### ISSUE THREAD

**Issue by thomasqueirozb** [kalekundert/vim-coiled-snake#21]
Strings do not seem to fold properly if there are more than 1 line break. Anything after the second line break is not recognized as part of the function

This is an example:
```python
def function():
    print(
        "This is a string that should \
be folded \
completely"
    )
    return true
```

After folding I get
```
def function():  ... (4)
completely"
    )
    return True
```

**Comment by kalekundert** [comment]
Thanks for the bug report!  I'll try to look into this tonight.

**Comment by kalekundert** [comment]
I think I fixed this bug, but let me know if the solution doesn't work for any reason.

**Comment by thomasqueirozb** [comment]
Thanks it works perfectly
