### ISSUE TITLE
Long Files Break Status Padding

### ISSUE THREAD

**Issue by ghickman** [kalekundert/vim-coiled-snake#3]
When using this plugin with a file that has over 1000 lines and line numbers turned on the closing parentheses is lost from the status line of a folded block.

Example:

![](https://cl.ly/1fa7f169c318/Image%202018-08-23%20at%2011.36.22%20am.png)

**Comment by kalekundert** [comment]
Thanks for the bug report.  I'll try to look into this later today.

**Comment by kalekundert** [comment]
I'm actually having trouble reproducing this.  I tried a few things, but it doesn't seem to be enough to simply have more than 1000 lines in the file, at least not with my ``vimrc``.  Do you think you could provide both the file that's causing problems and your ``vimrc`` file, or minimal versions of both?

**Comment by ghickman** [comment]
Sure thing!

Vimrc: https://github.com/ghickman/dotfiles/blob/master/vimrc
Problematic File: https://github.com/mozilla/treeherder/blob/master/treeherder/model/models.py

**Comment by kalekundert** [comment]
Yes, my problem was that I didn't have the `numbers` option set.  I think it's fixed now, let me know how it looks.

**Comment by ghickman** [comment]
Yep, this is working for me.  Thanks for fixing this @kalekundert!
