### ISSUE TITLE
Wrong fold with Black's multi-line function/method declaration

### ISSUE THREAD

**Issue by micku** [kalekundert/vim-coiled-snake#4]
When using the plugin with [Black](https://github.com/ambv/black) formatter, it doesn't recognize long functions/methods declaration indentation.

This is the [format](https://github.com/ambv/black#how-black-wraps-lines) used by Black:
```
def functionWithALotOfArgs(
    argument0,
    argument1,
    argument2,
    argument3,
    argument4,
    argument5,
    argument6,
    argument7,
    argument8,
    argument9,
):
    """This should be folded
    """
    pass
```

Here is the screenshot:
![image](https://user-images.githubusercontent.com/159038/44669324-e35c8680-aa1f-11e8-950b-46bfbb16653a.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/159038/44669491-4ea65880-aa20-11e8-81f3-861c49cfdfa2.png)

**Comment by kalekundert** [comment]
Thanks for the report.  It shouldn't be too hard to handle this formatting correctly, let me look into it.

**Comment by kalekundert** [comment]
Ok, I think this is handled correctly now.  Let me know if that's not the case. :-)

**Comment by micku** [comment]
It works! Would be great if this kind of fold shows func args like the inline one, but obviously it is not as important as the fold itself :)

Thank you @kalekundert!
